# Generated by Django 6.0.2 on 2026-05-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("order_created", "Order Created"),
                    ("order_paid", "Order Paid"),
                    ("order_shipped", "Order Shipped"),
                    ("system", "System"),
                ],
                db_column="type",
                max_length=50,
            ),
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="type",
            new_name="notification_type",
        ),
    ]
