# Generated by Django 6.0.2 on 2026-02-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_is_verified_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
