# Generated by Django 6.0.2 on 2026-02-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_emailverification_is_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverification",
            name="is_used",
        ),
    ]
