# Generated by Django 6.0.2 on 2026-05-01 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_emailverification_is_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=155,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username must contain only letters, numbers and allowed special characters.",
                        regex="^[a-zA-Z0-9._-]+$",
                    )
                ],
            ),
        ),
    ]
