# Generated by Django 6.0.2 on 2026-06-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="idx_product_owner",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="idx_product_category",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="idx_product_feed",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="catalog_pro_status_521020_idx",
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="owner",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
